on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: 
        dotnet build --configuration Release
    - name: Test
      run:
        dotnet test --configuration Release --no-build
  publish-nuget:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: dotnet test --configuration Release --no-build
