on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-and-Test
      working-directory: ./src
      run: 
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
  publish-nuget:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: dotnet test --configuration Release --no-build
